# Generated by Django 4.2.4 on 2023-08-27 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_courses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='course',
        ),
        migrations.AlterField(
            model_name='courses',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
